// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/allocations": {
            "get": {
                "description": "List allocations with optional status, base, quote, and role filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "List allocations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status. Supports comma-separated values.",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by base asset. Supports comma-separated values.",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by quote asset. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by crowding role. Supports comma-separated values.",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AllocationList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/allocations/active": {
            "get": {
                "description": "List allocations in created, running, failed, or paused state",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "Active allocations",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AllocationList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/allocations/cancelled": {
            "get": {
                "description": "List cancelled allocations with optional base, quote, role, and reason filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "Cancelled allocations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by base asset. Supports comma-separated values.",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by quote asset. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by crowding role. Supports comma-separated values.",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by normalized cancel reason. Supports comma-separated values.",
                        "name": "reason",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AllocationList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/allocations/cancelled/reasons": {
            "get": {
                "description": "Count cancelled allocations grouped by note/reason",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "Cancelled allocation reasons",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.CancelledReasonList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/allocations/running": {
            "get": {
                "description": "List allocations currently in running state",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "Running allocations",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AllocationList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/allocations/summary": {
            "get": {
                "description": "Count allocations by status and show active budget",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "Allocation summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AllocationSummary"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/allocations/{id}": {
            "get": {
                "description": "Get one allocation by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "Allocation detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Allocation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AllocationDetail"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/allocations/{id}/timeline": {
            "get": {
                "description": "Build allocation timeline from allocation, scaling, recovery, routing, and order progress tables",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "Allocation timeline",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Allocation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AllocationTimeline"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check API service and database status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Health"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/response.Health"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.Allocation": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "string"
                },
                "budget_usd": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "direction": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "note": {
                    "type": "string"
                },
                "pair": {
                    "type": "string"
                },
                "quote": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "score": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "worker_pid": {
                    "type": "string"
                }
            }
        },
        "response.AllocationDetail": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.Allocation"
                }
            }
        },
        "response.AllocationList": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Allocation"
                    }
                },
                "limit": {
                    "type": "integer"
                }
            }
        },
        "response.AllocationSummary": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "integer"
                },
                "active_budget_usd": {
                    "type": "string"
                },
                "by_status": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "cancelled": {
                    "type": "integer"
                },
                "cancelled_by_reason": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.CancelledReasonCount"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.AllocationTimeline": {
            "type": "object",
            "properties": {
                "allocation_id": {
                    "type": "integer"
                },
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AllocationTimelineEvent"
                    }
                }
            }
        },
        "response.AllocationTimelineEvent": {
            "type": "object",
            "properties": {
                "event": {
                    "type": "string"
                },
                "payload": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "reference_id": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "response.CancelledReasonCount": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "response.CancelledReasonList": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.CancelledReasonCount"
                    }
                },
                "limit": {
                    "type": "integer"
                }
            }
        },
        "response.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "response.Health": {
            "type": "object",
            "properties": {
                "checks": {
                    "$ref": "#/definitions/response.HealthChecks"
                },
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "response.HealthChecks": {
            "type": "object",
            "properties": {
                "api": {
                    "$ref": "#/definitions/response.HealthComponent"
                },
                "database": {
                    "$ref": "#/definitions/response.HealthComponent"
                }
            }
        },
        "response.HealthComponent": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Arbitrage VM CRM API",
	Description:      "CRM monitoring API for arbitrage trading system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
