// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/allocations": {
            "get": {
                "description": "List allocations with optional status, base, quote, and role filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "List allocations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status. Supports comma-separated values.",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by base asset. Supports comma-separated values.",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by quote asset. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by crowding role. Supports comma-separated values.",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AllocationList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/allocations/active": {
            "get": {
                "description": "List allocations in created, running, failed, or paused state",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "Active allocations",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AllocationList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/allocations/cancelled": {
            "get": {
                "description": "List cancelled allocations with optional base, quote, role, and reason filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "Cancelled allocations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by base asset. Supports comma-separated values.",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by quote asset. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by crowding role. Supports comma-separated values.",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by normalized cancel reason. Supports comma-separated values.",
                        "name": "reason",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AllocationList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/allocations/cancelled/reasons": {
            "get": {
                "description": "Count cancelled allocations grouped by note/reason",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "Cancelled allocation reasons",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.CancelledReasonList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/allocations/running": {
            "get": {
                "description": "List allocations currently in running state",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "Running allocations",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AllocationList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/allocations/summary": {
            "get": {
                "description": "Count allocations by status and show active budget",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "Allocation summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AllocationSummary"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/allocations/{id}": {
            "get": {
                "description": "Get one allocation by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "Allocation detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Allocation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AllocationDetail"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/allocations/{id}/timeline": {
            "get": {
                "description": "Build allocation timeline from allocation, scaling, recovery, routing, and order progress tables",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Allocations"
                ],
                "summary": "Allocation timeline",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Allocation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AllocationTimeline"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/equity/latest": {
            "get": {
                "description": "Temporarily fetch latest wallet/equity directly from exchange APIs with a short backend cache",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equity"
                ],
                "summary": "Latest equity from exchange API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by exchange: bybit, bitget. Supports comma-separated values.",
                        "name": "exchange",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "USDT",
                        "description": "Margin quote coins. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Bypass backend cache and pull from exchange API",
                        "name": "refresh",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.EquityLatest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/response.EquityLatest"
                        }
                    }
                }
            }
        },
        "/equity/live": {
            "get": {
                "description": "Temporarily fetch latest wallet/equity directly from exchange APIs with a short backend cache",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equity"
                ],
                "summary": "Latest equity from exchange API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by exchange: bybit, bitget. Supports comma-separated values.",
                        "name": "exchange",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "USDT",
                        "description": "Margin quote coins. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Bypass backend cache and pull from exchange API",
                        "name": "refresh",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.EquityLatest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/response.EquityLatest"
                        }
                    }
                }
            }
        },
        "/funding/history": {
            "get": {
                "description": "List historical funding rates",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Funding"
                ],
                "summary": "Funding history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by exchange. Supports comma-separated values.",
                        "name": "exchange",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by base asset. Supports comma-separated values.",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by quote asset. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Inclusive start time. Supports RFC3339 or YYYY-MM-DD.",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exclusive end time. Supports RFC3339 or YYYY-MM-DD.",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.FundingRateList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/funding/latest": {
            "get": {
                "description": "List latest funding rate per exchange and pair",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Funding"
                ],
                "summary": "Latest funding rates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by exchange. Supports comma-separated values.",
                        "name": "exchange",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by base asset. Supports comma-separated values.",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by quote asset. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.FundingRateList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/funding/spread": {
            "get": {
                "description": "Get latest Bybit versus Bitget funding spread for one pair",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Funding"
                ],
                "summary": "Funding spread",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Base asset",
                        "name": "base",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "USDT",
                        "description": "Quote asset",
                        "name": "quote",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.FundingSpreadDetail"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/funding/top-spreads": {
            "get": {
                "description": "List pairs with the largest absolute Bybit versus Bitget funding spread",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Funding"
                ],
                "summary": "Top funding spreads",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by base asset. Supports comma-separated values.",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by quote asset. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "default": 0,
                        "description": "Minimum absolute spread in bps",
                        "name": "min_abs_spread_bps",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.FundingSpreadList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check API service and database status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Health"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/response.Health"
                        }
                    }
                }
            }
        },
        "/market-quality/alerts": {
            "get": {
                "description": "List latest market quality rows that violate simple CRM thresholds",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Market Quality"
                ],
                "summary": "Market quality alerts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by exchange. Supports comma-separated values.",
                        "name": "exchange",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by base asset. Supports comma-separated values.",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by quote asset. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Alert when samples are below this value",
                        "name": "min_samples",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "default": 10,
                        "description": "Alert when spread_bps_p50 is above this value",
                        "name": "max_spread_bps_p50",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "default": 50,
                        "description": "Alert when mid speed p95 is above this value",
                        "name": "max_mid_speed_bps_per_sec_p95",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "default": 0.1,
                        "description": "Alert when depth stability ratio is below this value",
                        "name": "min_depth_stability_ratio",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.MarketQualityAlertList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/market-quality/history": {
            "get": {
                "description": "List historical market quality metrics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Market Quality"
                ],
                "summary": "Market quality history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by exchange. Supports comma-separated values.",
                        "name": "exchange",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by base asset. Supports comma-separated values.",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by quote asset. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Inclusive start time. Supports RFC3339 or YYYY-MM-DD.",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exclusive end time. Supports RFC3339 or YYYY-MM-DD.",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.MarketQualityList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/market-quality/latest": {
            "get": {
                "description": "List latest market quality metrics per exchange and pair",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Market Quality"
                ],
                "summary": "Latest market quality metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by exchange. Supports comma-separated values.",
                        "name": "exchange",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by base asset. Supports comma-separated values.",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by quote asset. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.MarketQualityList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/pnl/by-component": {
            "get": {
                "description": "Summarize PnL grouped by funding, trading_fee, and trading_pnl",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PnL"
                ],
                "summary": "PnL by component",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by exchange. Supports comma-separated values.",
                        "name": "exchange",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by base asset. Supports comma-separated values.",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by quote asset. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by component: funding, trading_fee, trading_pnl. Supports comma-separated values.",
                        "name": "component",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source type. Supports comma-separated values.",
                        "name": "source_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source id. Supports comma-separated values.",
                        "name": "source_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Inclusive start time. Supports RFC3339 or YYYY-MM-DD.",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exclusive end time. Supports RFC3339 or YYYY-MM-DD.",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PnLGroupList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/pnl/by-exchange": {
            "get": {
                "description": "Summarize PnL grouped by exchange",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PnL"
                ],
                "summary": "PnL by exchange",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by exchange. Supports comma-separated values.",
                        "name": "exchange",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by base asset. Supports comma-separated values.",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by quote asset. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by component: funding, trading_fee, trading_pnl. Supports comma-separated values.",
                        "name": "component",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source type. Supports comma-separated values.",
                        "name": "source_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source id. Supports comma-separated values.",
                        "name": "source_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Inclusive start time. Supports RFC3339 or YYYY-MM-DD.",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exclusive end time. Supports RFC3339 or YYYY-MM-DD.",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PnLGroupList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/pnl/by-pair": {
            "get": {
                "description": "Summarize PnL grouped by base and quote",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PnL"
                ],
                "summary": "PnL by pair",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by exchange. Supports comma-separated values.",
                        "name": "exchange",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by base asset. Supports comma-separated values.",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by quote asset. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by component: funding, trading_fee, trading_pnl. Supports comma-separated values.",
                        "name": "component",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source type. Supports comma-separated values.",
                        "name": "source_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source id. Supports comma-separated values.",
                        "name": "source_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Inclusive start time. Supports RFC3339 or YYYY-MM-DD.",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exclusive end time. Supports RFC3339 or YYYY-MM-DD.",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PnLGroupList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/pnl/events": {
            "get": {
                "description": "List persisted PnL ledger events",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PnL"
                ],
                "summary": "PnL events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by exchange. Supports comma-separated values.",
                        "name": "exchange",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by base asset. Supports comma-separated values.",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by quote asset. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by component: funding, trading_fee, trading_pnl. Supports comma-separated values.",
                        "name": "component",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source type. Supports comma-separated values.",
                        "name": "source_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source id. Supports comma-separated values.",
                        "name": "source_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Inclusive start time. Supports RFC3339 or YYYY-MM-DD.",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exclusive end time. Supports RFC3339 or YYYY-MM-DD.",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum rows to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PnLEventList"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/pnl/summary": {
            "get": {
                "description": "Summarize PnL totals and grouped breakdowns",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PnL"
                ],
                "summary": "PnL summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by exchange. Supports comma-separated values.",
                        "name": "exchange",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by base asset. Supports comma-separated values.",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by quote asset. Supports comma-separated values.",
                        "name": "quote",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by component: funding, trading_fee, trading_pnl. Supports comma-separated values.",
                        "name": "component",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source type. Supports comma-separated values.",
                        "name": "source_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source id. Supports comma-separated values.",
                        "name": "source_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Inclusive start time. Supports RFC3339 or YYYY-MM-DD.",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exclusive end time. Supports RFC3339 or YYYY-MM-DD.",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum grouped rows per breakdown",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PnLSummary"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/system/exchanges": {
            "get": {
                "description": "List supported exchanges and latest market-data timestamps",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "System exchanges",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SystemExchangeList"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/system/status": {
            "get": {
                "description": "Get API, database, TimescaleDB, market-data, allocation, and exchange status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "System status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SystemStatus"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/response.SystemStatus"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.Allocation": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "string"
                },
                "budget_usd": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "direction": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "note": {
                    "type": "string"
                },
                "pair": {
                    "type": "string"
                },
                "quote": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "score": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "worker_pid": {
                    "type": "string"
                }
            }
        },
        "response.AllocationDetail": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.Allocation"
                }
            }
        },
        "response.AllocationList": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Allocation"
                    }
                },
                "limit": {
                    "type": "integer"
                }
            }
        },
        "response.AllocationSummary": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "integer"
                },
                "active_budget_usd": {
                    "type": "string"
                },
                "by_status": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "cancelled": {
                    "type": "integer"
                },
                "cancelled_by_reason": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.CancelledReasonCount"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.AllocationTimeline": {
            "type": "object",
            "properties": {
                "allocation_id": {
                    "type": "integer"
                },
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AllocationTimelineEvent"
                    }
                }
            }
        },
        "response.AllocationTimelineEvent": {
            "type": "object",
            "properties": {
                "event": {
                    "type": "string"
                },
                "payload": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "reference_id": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "stage": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "response.CancelledReasonCount": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "response.CancelledReasonList": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.CancelledReasonCount"
                    }
                },
                "limit": {
                    "type": "integer"
                }
            }
        },
        "response.CombinedEquity": {
            "type": "object",
            "properties": {
                "account_equity": {
                    "type": "string"
                },
                "available_balance": {
                    "type": "string"
                },
                "initial_margin": {
                    "type": "string"
                },
                "maintenance_margin": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "unrealized_pnl": {
                    "type": "string"
                },
                "wallet_balance": {
                    "type": "string"
                }
            }
        },
        "response.EquityCoin": {
            "type": "object",
            "properties": {
                "available_balance": {
                    "type": "string"
                },
                "coin": {
                    "type": "string"
                },
                "equity": {
                    "type": "string"
                },
                "locked": {
                    "type": "string"
                },
                "unrealized_pnl": {
                    "type": "string"
                },
                "usd_value": {
                    "type": "string"
                },
                "wallet_balance": {
                    "type": "string"
                }
            }
        },
        "response.EquityFetchError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "exchange": {
                    "type": "string"
                }
            }
        },
        "response.EquityLatest": {
            "type": "object",
            "properties": {
                "cache_ttl_seconds": {
                    "type": "integer"
                },
                "combined": {
                    "$ref": "#/definitions/response.CombinedEquity"
                },
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.EquitySnapshot"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.EquityFetchError"
                    }
                }
            }
        },
        "response.EquitySnapshot": {
            "type": "object",
            "properties": {
                "account_equity": {
                    "type": "string"
                },
                "available_balance": {
                    "type": "string"
                },
                "cached": {
                    "type": "boolean"
                },
                "coins": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.EquityCoin"
                    }
                },
                "exchange": {
                    "type": "string"
                },
                "initial_margin": {
                    "type": "string"
                },
                "maintenance_margin": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "unrealized_pnl": {
                    "type": "string"
                },
                "wallet_balance": {
                    "type": "string"
                }
            }
        },
        "response.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "response.FundingRate": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "string"
                },
                "exchange": {
                    "type": "string"
                },
                "funding_rate": {
                    "type": "string"
                },
                "pair": {
                    "type": "string"
                },
                "quote": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "response.FundingRateList": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.FundingRate"
                    }
                },
                "limit": {
                    "type": "integer"
                }
            }
        },
        "response.FundingSpread": {
            "type": "object",
            "properties": {
                "abs_spread_bps": {
                    "type": "string"
                },
                "base": {
                    "type": "string"
                },
                "bitget_rate": {
                    "type": "string"
                },
                "bitget_time": {
                    "type": "string"
                },
                "bybit_rate": {
                    "type": "string"
                },
                "bybit_time": {
                    "type": "string"
                },
                "direction_hint": {
                    "type": "string"
                },
                "pair": {
                    "type": "string"
                },
                "quote": {
                    "type": "string"
                },
                "spread": {
                    "type": "string"
                },
                "spread_bps": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "response.FundingSpreadDetail": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.FundingSpread"
                }
            }
        },
        "response.FundingSpreadList": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.FundingSpread"
                    }
                },
                "limit": {
                    "type": "integer"
                }
            }
        },
        "response.Health": {
            "type": "object",
            "properties": {
                "checks": {
                    "$ref": "#/definitions/response.HealthChecks"
                },
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "response.HealthChecks": {
            "type": "object",
            "properties": {
                "api": {
                    "$ref": "#/definitions/response.HealthComponent"
                },
                "database": {
                    "$ref": "#/definitions/response.HealthComponent"
                }
            }
        },
        "response.HealthComponent": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.MarketQualityAlert": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "string"
                },
                "depth_stability_ratio": {
                    "type": "string"
                },
                "exchange": {
                    "type": "string"
                },
                "mid_speed_bps_per_sec_p95": {
                    "type": "string"
                },
                "pair": {
                    "type": "string"
                },
                "quote": {
                    "type": "string"
                },
                "reasons": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "samples": {
                    "type": "integer"
                },
                "spread_bps_p50": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "response.MarketQualityAlertList": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MarketQualityAlert"
                    }
                },
                "limit": {
                    "type": "integer"
                }
            }
        },
        "response.MarketQualityList": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MarketQualityMetric"
                    }
                },
                "limit": {
                    "type": "integer"
                }
            }
        },
        "response.MarketQualityMetric": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "string"
                },
                "depth_stability_ratio": {
                    "type": "string"
                },
                "exchange": {
                    "type": "string"
                },
                "mid_speed_bps_per_sec_p95": {
                    "type": "string"
                },
                "pair": {
                    "type": "string"
                },
                "quote": {
                    "type": "string"
                },
                "samples": {
                    "type": "integer"
                },
                "spread_bps_p50": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "response.PnLEvent": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "base": {
                    "type": "string"
                },
                "component": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "event_time": {
                    "type": "string"
                },
                "exchange": {
                    "type": "string"
                },
                "pair": {
                    "type": "string"
                },
                "quote": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                }
            }
        },
        "response.PnLEventList": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PnLEvent"
                    }
                },
                "limit": {
                    "type": "integer"
                }
            }
        },
        "response.PnLGroup": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "string"
                },
                "component": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "exchange": {
                    "type": "string"
                },
                "first_event_time": {
                    "type": "string"
                },
                "funding_amount": {
                    "type": "string"
                },
                "last_event_time": {
                    "type": "string"
                },
                "pair": {
                    "type": "string"
                },
                "quote": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "string"
                },
                "trading_fee_amount": {
                    "type": "string"
                },
                "trading_pnl_amount": {
                    "type": "string"
                }
            }
        },
        "response.PnLGroupList": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PnLGroup"
                    }
                },
                "limit": {
                    "type": "integer"
                }
            }
        },
        "response.PnLSummary": {
            "type": "object",
            "properties": {
                "by_component": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PnLGroup"
                    }
                },
                "by_exchange": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PnLGroup"
                    }
                },
                "by_pair": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PnLGroup"
                    }
                },
                "count": {
                    "type": "integer"
                },
                "funding_amount": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "string"
                },
                "trading_fee_amount": {
                    "type": "string"
                },
                "trading_pnl_amount": {
                    "type": "string"
                }
            }
        },
        "response.SystemAllocationStatus": {
            "type": "object",
            "properties": {
                "last_updated_at": {
                    "type": "string"
                },
                "running": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.SystemExchange": {
            "type": "object",
            "properties": {
                "credential_configured": {
                    "type": "boolean"
                },
                "demo": {
                    "type": "boolean"
                },
                "enabled": {
                    "type": "boolean"
                },
                "exchange": {
                    "type": "string"
                },
                "last_account_event_at": {
                    "type": "string"
                },
                "last_funding_at": {
                    "type": "string"
                },
                "last_market_data_at": {
                    "type": "string"
                },
                "last_market_quality_at": {
                    "type": "string"
                },
                "last_open_interest_at": {
                    "type": "string"
                },
                "last_wallet_snapshot_at": {
                    "type": "string"
                },
                "notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "supported": {
                    "type": "boolean"
                }
            }
        },
        "response.SystemExchangeList": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.SystemExchange"
                    }
                }
            }
        },
        "response.SystemMarketDataStatus": {
            "type": "object",
            "properties": {
                "funding_last_at": {
                    "type": "string"
                },
                "market_quality_last_at": {
                    "type": "string"
                },
                "open_interest_last_at": {
                    "type": "string"
                }
            }
        },
        "response.SystemStatus": {
            "type": "object",
            "properties": {
                "allocations": {
                    "$ref": "#/definitions/response.SystemAllocationStatus"
                },
                "api_version": {
                    "type": "string"
                },
                "database": {
                    "$ref": "#/definitions/response.HealthComponent"
                },
                "exchanges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.SystemExchange"
                    }
                },
                "market_data": {
                    "$ref": "#/definitions/response.SystemMarketDataStatus"
                },
                "status": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "timescale": {
                    "$ref": "#/definitions/response.HealthComponent"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Arbitrage VM CRM API",
	Description:      "CRM monitoring API for arbitrage trading system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
